language: go
go:
  - '1.5' 
install:
  - "go get -d -v ./..."
  - "go build -v ./..."
deploy:
  provider: releases
  api_key:
    secure: oBIgBA1opU0pXDL+uKJEYGupkI8Ynoda2jFShZJ267ijzkiWdu3Z0Ee4gO9IP2geBPgDpQbK2IcAqLNJZmRjtrWFH7tBWrJa2uIaYdOZPhQHdKHpYpKkorudOJmew29B9uCRA15sI6F4F9XuN/kj5bkpGNDJzaaZRRDOoJVagD8X0hrVSGtg3u5qT3PvFYpweV7I9RXYVnu1n66/W9Gb+UOefkgWt8CLGN/s7qsHEYNobxR+rT2KH3EQf75vUCM8ocJNRuw9bbpZjyta/RsOlVc/NSY8x7OiK7qWWngdxrwtg3/djxT8SgMsoSVHsp05sm4mWiJRFPBzBNnOfmduFJd1QSI91/+d5mQnIMibzFEU7XSzR0lmYB6xxy/hu6IVBFbdVKS/yaBHLMkuJld+zydXPe/1rOBwNZUVnx5ZVVmWwrASb5NIbec1gdEmcJVF+ctVMm52EQ7WeER2Kq7g4CSkMnE8R1YqGhhQd4vTD2rJjkT9/YjVI/X9agK1jaVdrTaDbkerUKabadjGf20a14GnbWkqiH32t4TF3Gg0kf3r2D3cgpUeBodSA2JZqDTib91I3U2QU6jVQwj0W9X2swxfuEL1pYVgjEDotsadykOYFrvrAzGdcKKOgjO16buBFHDD8kswNapUgioF2824c7kboedRR9MSNI66UteCfEI=
  skip_cleanup: true
  on:
    repo: cha87de/kvmtop
    tags: true
